import '../data/models/note_model.dart';
import '../data/repositories/home_repository.dart';

class NoteController {
  final NoteRepository noteRepository;

  NoteController({required this.noteRepository});

  Future<List<NoteModel>> getAllNotes() async {
    return noteRepository.getAllNotes();
  }

  Future<int> addNote({
    required String title,
    required String content,
    required String language,
    required String timeStamp,
    required String dateStamp,
  }) async {
    final NoteModel note = NoteModel(
        id: 0, // The actual ID will be generated by the repository
        title: title,
        content: content,
        language: language,
        timeStamp: timeStamp,
        dateStamp: dateStamp);

    return noteRepository.addNote(note);
  }

  Future<void> updateNote({
    required int id,
    required String title,
    required String content,
    required String language,
    required String timeStamp,
    required String dateStamp,
  }) async {
    final NoteModel note = NoteModel(
        id: id,
        title: title,
        content: content,
        language: language,
        timeStamp: timeStamp,
        dateStamp: dateStamp);

    await noteRepository.updateNote(note);
  }

  Future<void> deleteNote({
    required int id,
  }) async {
    await noteRepository.deleteNote(id);
  }
}
